name: m7_livelyness_detection
description: A single function package to detect weather the face visible in the camera is a live face or not.
version: 0.0.4+5
homepage: https://github.com/Meet-7-dating/m7_livelyness_detection
repository: https://github.com/Meet-7-dating/m7_livelyness_detection/
issue_tracker: https://github.com/Meet-7-dating/m7_livelyness_detection/issues

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  animate_do: ^3.1.2
  camera: ^0.10.5+5
  camerawesome: ^2.0.0-dev.1
  collection: 1.17.2
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.8.0
  image: ^4.1.3
  lottie: ^2.7.0
  plugin_platform_interface: ^2.1.6
  rxdart: ^0.27.7
  uuid: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.m7_livelyness_detection
        pluginClass: M7LivelynessDetectionPlugin
      ios:
        pluginClass: M7LivelynessDetectionPlugin

  # To add assets to your plugin package, add an assets section, like this:
  assets:
    - packages/m7_livelyness_detection/src/assets/lottie/livelyness-start.json
    - packages/m7_livelyness_detection/src/assets/lottie/livelyness-success.json
    - packages/m7_livelyness_detection/src/assets/lottie/step_completed.json
    - packages/m7_livelyness_detection/src/assets/final-mesh.png